# Generated by Django 5.2.6 on 2025-09-17 09:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_groups_student_is_staff_student_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=True),
        ),
    ]
