# Generated by Django 5.2.6 on 2025-09-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_created_at_alter_student_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(),
        ),
    ]
