# Generated by Django 5.1.1 on 2025-09-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='faculty_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='faculty_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
