# Generated by Django 5.1.1 on 2025-09-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_submission_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='faculty_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
