# Generated by Django 5.1.1 on 2025-09-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_submission_faculty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='faculty_remarks',
            field=models.TextField(null=True),
        ),
    ]
