# Generated by Django 5.1.1 on 2025-09-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_submission_faculty_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='faculty_remarks',
            field=models.TextField(blank=True),
        ),
    ]
