# Generated by Django 5.1.1 on 2025-09-27 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_submission_faculty_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='faculty_name',
        ),
    ]
