# Generated by Django 5.1.1 on 2025-09-27 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminui', '0005_problem_created_by'),
        ('student', '0015_remove_submission_faculty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_submissions', to='adminui.faculty'),
        ),
    ]
