# Generated by Django 5.2.6 on 2025-09-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminui', '0002_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='category',
        ),
        migrations.AddField(
            model_name='problem',
            name='total_marks',
            field=models.CharField(default=100, max_length=100),
        ),
    ]
