# Generated by Django 5.1.1 on 2025-09-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminui', '0003_remove_problem_category_problem_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='total_marks',
            field=models.IntegerField(),
        ),
    ]
