# Generated by Django 5.1.1 on 2025-09-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminui', '0005_problem_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
